[package]
name = "pilot"
version = "0.1.0"
edition = "2021"

[dependencies]
global-hotkey = "0.6.2"
winit = "0.30.5"

[target.'cfg(target_os = "macos")'.dependencies]
accessibility-sys = "0.1.3"
core-foundation = "0.10.0"
core-foundation-sys = "0.8.7"
core-graphics = "0.24.0"
